apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: update-rhacs-policies
spec:
  params: 
    - name: "git-repo-revision"
      value: "main"
    - name: "git-repo-url"
      value: "https://github.com/shaneboulden/ansible-acs-policy-demo.git"
    - name: "context-dir"
      value: "/"
    - name: "project-dir"
      value: "."
    - name: "rhacs-secret"
      value: "tkn-rhacs"
  pipelineRef:
    name: update-rhacs-policies
  workspaces:
    - name: ansible
      persistentVolumeClaim:
        claimName: pipeline-pvc