---
- name: Perform an initial batch policy pull from ACS
  hosts: localhost
  gather_facts: false

  vars:
    acs_host: "{{ lookup('ansible.builtin.env','RHACS_URL') }}"
    acs_token: "{{ lookup('ansible.builtin.env','RHACS_TOKEN') }}"

  tasks:

  - name: Get policies from ACS
    vars:
      dest_path: '../acs-policy-files'
    include_tasks:
      file: tasks/get_policies.yml
